name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        env:
            RUSTFLAGS: '-Dwarnings'

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy, rustfmt

            - name: Install crates
              run: cargo install cargo-deny cargo-machete

            - name: Lint
              run: cargo clippy --all-features --locked

            - name: Check formatting
              run: cargo fmt --all --check

            - name: Check dependencies
              run: cargo deny check

            - name: Check unused dependencies
              run: cargo machete

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy, rustfmt

            - name: Test
              run: cargo test --all-features --locked --release
