name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: RustForWeb/.github/.github/workflows/release.yml@c18f3b7315df398b6af8d03f823e31daeda63114
        with:
            bump: ${{ inputs.bump }}
